### ISSUE TITLE
Finalize breakpoint 

### ISSUE THREAD

**Issue by mkbansal1** [hlxsites/fonterra-fernleaf#10]
Current fernleaf site use below breakpoints:
Vlarge (Desktop): >=1024px, 1280px, 1440px 
Large (Tab): 768px - 1023px 
Small (Mobile): 321px - 767px 
Very Small: < 320px

Franklin provides below breakpoints ootb
600px, 900px, 1200px

@asthabh23  Please finalize with the business and confirm the exact breakpoints.

**Comment by asthabh23** [comment]
This has been discussed, finalised to proceed with default media breakpoints
