### ISSUE TITLE
Fix styles for CalciYum page

### ISSUE THREAD

**Issue by gauthamksn** [hlxsites/fonterra-fernleaf#104]
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/a7811443-870b-4736-b731-b1bc6952cd57)

link: https://main--fonterra-fernleaf--hlxsites.hlx.page/en/products/calciyum

**Expected:**
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/e8cb59ec-bcbd-4c15-8c1d-f6a6a5dd4827)
link: https://www.fernleaf.com.my/en/products/calciyum.html

**Comment by noormd08** [comment]
Issue resolved. Raised PR https://github.com/hlxsites/fonterra-fernleaf/pull/136

As per the internal discussion, the "product" and "recipe" needs to be passed in block level instead of parent (body) level. This will solve the issues when product image is not presented.

**Comment by noormd08** [comment]
Changes are done. Kept Recipe as default and  Main & Product as variations with additional class name in block level.
