### ISSUE TITLE
[Authoring] Product landing page

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/fonterra-fernleaf#106]
Cards block layout seems to be pending yet. Needs to be inline with https://www.hlx.live/developer/block-collection/cards

**Comment by gauthamksn** [comment]
@asthabh23 I have updated all the cards blocks to follow the layout. Please validate.

**Comment by mkbansal1** [comment]
We are using cards only on the product listing page in both languages.

**Comment by asthabh23** [comment]
lgtm! thanks!
