### ISSUE TITLE
[404 page translation] Translation of content for English and Malay Languages

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/fonterra-fernleaf#107]
reference:
https://github.com/hlxsites/airlessco/blob/1ea0584aff0fc75858cea75085e752ad903c8f3c/scripts/scripts.js#L232-L251

where the 404.html contains a JS file, which identifies the language, fetches /ms/404.plain.html and overwrites the content via `innerHTML`

**Comment by mkbansal1** [comment]
@asthabh23 This solution adds a jerk
https://main--airlessco--hlxsites.hlx.live/emea/pl/products/linestripers/dsd

I suggest using placeholders instead.

**Comment by asthabh23** [comment]
@mkbansal1 , I was checking on the same lines.. we have another reply on the same slack channel thread, please have a look meanwhile on the options suggested. Placeholders seems to be a good approach as we have less content too.
