### ISSUE TITLE
Fix Styles for Privacy Policy and Terms and Conditions pages

### ISSUE THREAD

**Issue by gauthamksn** [hlxsites/fonterra-fernleaf#114]
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/1571bb7f-10e3-498f-9687-d4b59add9304)

link: https://main--fonterra-fernleaf--hlxsites.hlx.live/en/terms-and-conditions
**Expected:**
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/53826da0-24d8-427a-b914-f6d3df98f5a5)
link: https://www.fernleaf.com.my/en/terms-and-conditions.html

**Comment by asthabh23** [comment]
@mkbansal1 @sselvara 
this seems a small change around just modifying the headings, can we expect this to be closed by today?
please consider this as P1
