### ISSUE TITLE
[Product Detail Pages - for lesser viewports] Content Alignment fixes + Accordion with table

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/fonterra-fernleaf#117]
https://main--fonterra-fernleaf--hlxsites.hlx.page/en/products/protein-plus-milk-powder

- [ ] Text alignment is touching the boundaries. Margins need to be added, also font size needs fix
<img width="611" alt="Screenshot 2023-08-16 at 6 57 13 PM" src="https://github.com/hlxsites/fonterra-fernleaf/assets/76686725/c0b74bff-94ac-4e8e-9d82-2a40c00dc88c">

Original site:
<img width="514" alt="Screenshot 2023-08-16 at 6 57 42 PM" src="https://github.com/hlxsites/fonterra-fernleaf/assets/76686725/356797a0-4009-4b8f-8430-c92f8e6029cb">

- [ ] Table in accordion has missing columns for lesser media width:

Expected:
<img width="490" alt="Screenshot 2023-08-16 at 6 59 24 PM" src="https://github.com/hlxsites/fonterra-fernleaf/assets/76686725/478a4c45-2910-434f-beb0-18370c522d47">

Current Franklin site implementation:
<img width="525" alt="Screenshot 2023-08-16 at 7 00 09 PM" src="https://github.com/hlxsites/fonterra-fernleaf/assets/76686725/c524bb1a-8027-4fe4-bb81-b3191d001e76">

**Comment by asthabh23** [comment]
@mkbansal1 @sselvara 
is something around this still in progress in any PR? or yet to be raised?

**Comment by sselvara** [comment]
@asthabh23 Fixed as part of the PR #120.

**Comment by asthabh23** [comment]
@mkbansal1 @sselvara 
The nutrition benefits accordion seems to be out of alignment for lesser viewports.

Franklin implementation:
<img width="503" alt="Screenshot 2023-08-22 at 11 29 30 AM" src="https://github.com/hlxsites/fonterra-fernleaf/assets/76686725/a45b03a1-f9d5-4905-97fd-a1f71625e3db">

Original site:
<img width="494" alt="Screenshot 2023-08-22 at 11 29 50 AM" src="https://github.com/hlxsites/fonterra-fernleaf/assets/76686725/0f55c750-af62-4319-bf61-bec80a7090a7">

**Comment by sselvara** [comment]
@asthabh23  this will be fixed as part of https://github.com/hlxsites/fonterra-fernleaf/pull/172, it seems that the code is overridden in columns.css file as things are fine in this branch https://138-buy-options--fonterra-fernleaf--hlxsites.hlx.page/en/products/milk-powder-for-whole-family. Copied the missing code and created the PR

**Comment by asthabh23** [comment]
ok, thanks! rest seems fine
