### ISSUE TITLE
[Carousel Images] Fix for image sizes

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/fonterra-fernleaf#121]
@ujjwal5 , continuing on your comment in other PR, I would consider having a width/height set for the images so it is not uneven on different viewports.

Looks like issue is basically with the images used. This is happening for certain images only, for example:

choco pot desert
koko smoothie
pizza gulung
tropical breakfast cups
ice cream payasam (circle)
mango pudding
indian tahini
crumbled stuffed pears

**Comment by ujjwal5** [comment]
https://122-remove-horizontal-scroll--fonterra-fernleaf--hlxsites.hlx.page/en/recipes/buttermilk-chicken
