### ISSUE TITLE
[UAT] Product Details Pages - Accordion

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/fonterra-fernleaf#124]
https://main--fonterra-fernleaf--hlxsites.hlx.live/en/products/uht-milk

On all the product pages the 'nutrition' accordion to be expanded on page load and other (full cream) be collapsed.

**Comment by gauthamksn** [comment]
Please test this feature using this page.
https://main--fonterra-fernleaf--hlxsites.hlx.page/drafts/gautham/products/milk-powder-for-whole-family
