### ISSUE TITLE
Fix Padding issue in stories and tips page for lesser views

### ISSUE THREAD

**Issue by gauthamksn** [hlxsites/fonterra-fernleaf#126]
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/7a174d4d-7bd7-44b1-94db-9b387b0af886)

Link : https://main--fonterra-fernleaf--hlxsites.hlx.page/ms/artikel-menarik

**Expected**

![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/9a81a3f0-924d-4e91-a20c-b2d39217c066)

Link: https://www.fernleaf.com.my/ms/artikel-menarik.html

**Comment by asthabh23** [comment]
TO add: full width CTA for lesser views
