### ISSUE TITLE
[Search] Layout of listed Products and Recipes

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/fonterra-fernleaf#131]
Two column layout to be handled between 900px - 1200px

**Comment by noormd08** [comment]
This has been handled by reducing 60px for RHS section and the relevant fields are adjusted based on it.
PR https://github.com/hlxsites/fonterra-fernleaf/pull/133 contains the fixes along with other changes.

**Comment by noormd08** [comment]
@asthabh23 Please verify the changes.
https://main--fonterra-fernleaf--hlxsites.hlx.page/en

**Comment by asthabh23** [comment]
lgtm!
