### ISSUE TITLE
[404 page] Malay version

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/fonterra-fernleaf#139]
For Malay version, let's proceed with using google translation to translate it to Malay from English.

We will get this validated from client during UAT.

**Comment by mkbansal1** [comment]
Updated the translations. Please check and close this card.
https://main--fonterra-fernleaf--hlxsites.hlx.live/ms/dssd

<img width="1118" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/78f47cbb-e382-4357-915d-3123dedb98dd">

**Comment by asthabh23** [comment]
@mkbansal1 The alignment of text and layout as a whole is different, please consider aligning/styling it as per the original URL for the content part
<img width="626" alt="Screenshot 2023-08-18 at 11 40 44 AM" src="https://github.com/hlxsites/fonterra-fernleaf/assets/76686725/95058336-53df-4b69-9f15-221e79bb43de">

**Comment by mkbansal1** [comment]
@asthabh23 Live site use 404 page of Fonterra, so Fonterra design is rendered.

As we have created 404 page for Fernleaf, it has Fernleaf theme.

**Comment by asthabh23** [comment]
ok, I will ask the customer to validate this as part of UAT. for now I added the relevant label

**Comment by asthabh23** [comment]
This has been shared with customer
