### ISSUE TITLE
[Hero] Implement hero banner

### ISSUE THREAD

**Issue by mkbansal1** [hlxsites/fonterra-fernleaf#14]
- [x] Hero banner on the home page
- [x] Hero banner with background image and overlayed text
- [x] Hero banner with two background images (Product pages) & overlayed splash image
- [x] Hero banner with one background image (Recipe pages) & overlayed splash image
- [x] Support adaptive images - different images for desktop and mobile

**Comment by mkbansal1** [comment]
Implemented the logic to handle different usecases of hero banner.

**Comment by asthabh23** [comment]
@mkbansal1 , do we have latest implementation for this at content side completed? It would be great to have these in place in the site pages word docs as needed (maybe as a draft?) and then build those on top of it.

**Comment by mkbansal1** [comment]
@asthabh23 I have placed all variations of hero banner on this page
https://14-implement-hero-banner--fonterra-fernleaf--hlxsites.hlx.live/en/banner?view-doc-source=true

**Comment by asthabh23** [comment]
great! thanks @mkbansal1 
for the other pages like recipes one, is it still under progress?

**Comment by mkbansal1** [comment]
We are covering all variations of hero banner (home, recipe, product pages) with single hero block. It's currently in progress.

**Comment by noormd08** [comment]
All the changes are done and incorporated in the sample banner page. However need to have a discussion on the container part to be used throughout application

**Comment by noormd08** [comment]
Container part is also incorporated and raised the PR.
