### ISSUE TITLE
[Authoring] Add metadata on listing pages

### ISSUE THREAD

**Issue by mkbansal1** [hlxsites/fonterra-fernleaf#144]
Add metadata (title, description) on listing pages - product listing, recipe listing, story n tips listing (both languages)

Due to missing metadata, the below error appears
Report: https://pagespeed.web.dev/analysis/https-main--fonterra-fernleaf--hlxsites-hlx-live-en-stories-and-tips/gq1ekd59rl?form_factor=mobile
Page: https://main--fonterra-fernleaf--hlxsites.hlx.live/en/stories-and-tips
<img width="947" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/be527088-ca80-426f-b104-b462888daa16">

**Comment by gauthamksn** [comment]
Metadata added. Please validate.

**Comment by mkbansal1** [comment]
Looks good
