### ISSUE TITLE
Hero - Add variation on product pages

### ISSUE THREAD

**Issue by mkbansal1** [hlxsites/fonterra-fernleaf#150]
Add a variation "has-product" on all product pages (Except calcium) for both languages.
Reference: https://main--fonterra-fernleaf--hlxsites.hlx.live/en/products/yogurt

![image](https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/db229e61-3a2e-466f-80cf-fa97670cdca1)

**Comment by gauthamksn** [comment]
Updated all product pages. Please validate.

**Comment by mkbansal1** [comment]
Looks good, closing this card
