### ISSUE TITLE
[LCP] Preload Largest Contentful Paint image issue 

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/fonterra-fernleaf#151]
<img width="979" alt="Screenshot 2023-08-18 at 1 04 40 PM" src="https://github.com/hlxsites/fonterra-fernleaf/assets/76686725/abd3ee05-4589-4732-9dbb-d9f3b84de464">

**Comment by mkbansal1** [comment]
@asthabh23 Even after setting width to 400px, we are getting the same LCP issue
URL: https://151-lcp-preload--fonterra-fernleaf--hlxsites.hlx.live/en
PageSpeed: https://pagespeed.web.dev/analysis/https-151-lcp-preload--fonterra-fernleaf--hlxsites-hlx-live-en/2smgzqo5by?form_factor=mobile

<img width="1338" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/f475b34b-f8e3-4351-a56b-b3d1abcf9aa1">

**Comment by asthabh23** [comment]
@mkbansal1 
We have fixed the major LHS drop which was around GTM integration.
This LCP warning is not an issue. I think PSI numbers are good now, we will get back if really required, closing this issue for now
