### ISSUE TITLE
Product pages - change Nutrition to use h2 instead of h3

### ISSUE THREAD

**Issue by ujjwal5** [hlxsites/fonterra-fernleaf#157]
This is required to fix accessibility issue we are getting in product pages. 
[Heading elements are not in a sequentially-descending order]

One such product page has been fixed with this: https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B52F9EFE3-C424-46A4-829D-46AE43AA4B49%7D&file=milk-powder-for-whole-family.docx&action=default&mobileredirect=true

**Comment by asthabh23** [comment]
@mkbansal1 , is this completed and fixed on all required pages?

**Comment by mkbansal1** [comment]
Its completed for english, @gauthamksn  will complete this activity today.

**Comment by mkbansal1** [comment]
All pages are updated. Closing this card
