### ISSUE TITLE
Add bg image at bottom of recipes listing page.

### ISSUE THREAD

**Issue by gauthamksn** [hlxsites/fonterra-fernleaf#162]
Recipe list page does not have a background image and margin before footer ( after all the recipe cards )

Links:

- https://main--fonterra-fernleaf--hlxsites.hlx.page/en/recipes
- https://www.fernleaf.com.my/en/recipes.html

![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/4d3c24c0-800f-44d5-91d7-74c847946a03)
Expected:
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/f2064d14-03b5-4bea-823d-a7e9a266ed80)

**Comment by sselvara** [comment]
@ParthasharathiB  add bg for category page as well.

https://104-hero-banner-fix--fonterra-fernleaf--hlxsites.hlx.page/en/products/calciyum
