### ISSUE TITLE
[UAT][Authoring] Product Details Pages - Accordion 

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/fonterra-fernleaf#165]
At authoring side, we will add "expand" keyword in accordion block corresponding to Nutrition Benefits and handle the same at code level.

This would give authoring control - accordion field with "expand" keyword would be open on load and when no keyword is added, by default the accordion would be closed/collapsed

This is related to #124

**Comment by gauthamksn** [comment]
@asthabh23 I have updated all the products in my draft folder. Please validate.

**Comment by asthabh23** [comment]
Hi @gauthamksn 
since the code is already merged in `main`, we should be good to update the main product pages at authoring level and then do a final test.. could you please do that confirm once done?

**Comment by gauthamksn** [comment]
Main product pages are also updated now.

**Comment by gauthamksn** [comment]
That was also done. All pages are working fine.

**Comment by asthabh23** [comment]
great! thanks, conveyed to customer
