### ISSUE TITLE
[Search] for lesser viewports

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/fonterra-fernleaf#174]
Animated text should not come up for lesser viewports

@noormd08 @mkbansal1 @sselvara please fix this
<img width="494" alt="Screenshot 2023-08-22 at 12 18 37 PM" src="https://github.com/hlxsites/fonterra-fernleaf/assets/76686725/36971e29-316f-4c57-83b7-558e2ee81122">

**Comment by asthabh23** [comment]
also for "milk" keyword, in Others section, a lot of unrelated links come up... please check

**Comment by noormd08** [comment]
@asthabh23 Please check in the latest. We just fixed it.
https://146-search-tags--fonterra-fernleaf--hlxsites.hlx.page/en
https://main--fonterra-fernleaf--hlxsites.hlx.page/en

**Comment by asthabh23** [comment]
I still see it though @noormd08

**Comment by asthabh23** [comment]
@noormd08 , please link this GH issue to your PR which has the fix for it

**Comment by noormd08** [comment]
Fixed as a part of https://github.com/hlxsites/fonterra-fernleaf/issues/146

PR: https://github.com/hlxsites/fonterra-fernleaf/pull/173

**Comment by asthabh23** [comment]
lgtm now!
