### ISSUE TITLE
Splash image issue

### ISSUE THREAD

**Issue by sselvara** [hlxsites/fonterra-fernleaf#177]
There is a slight alignment issue of splash image between original and current implementations.

Original:
https://www.fernleaf.com.my/en/products/calciyum/calciyum-milk-powder.html
<img width="1818" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/25244481/0e7767e9-6826-4866-b6fd-d6edf2e587e4">

Current:
https://main--fonterra-fernleaf--hlxsites.hlx.page/en/products/calciyum/calciyum-milk-powder
<img width="1815" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/25244481/1fdc0fe4-f8d9-43fb-8346-e17f2575ee10">

**Comment by asthabh23** [comment]
deprioritising
