### ISSUE TITLE
Add Gifs to stories pages

### ISSUE THREAD

**Issue by gauthamksn** [hlxsites/fonterra-fernleaf#181]
Links:

- https://www.fernleaf.com.my/ms/artikel-menarik/jangan-lupa-pantau-diet-anak-anda-di-rumah.html
- https://main--fonterra-fernleaf--hlxsites.hlx.page/ms/artikel-menarik/jangan-lupa-pantau-diet-anak-anda-di-rumah

![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/a458e073-fd68-4db7-965e-750c12ce88b3)

**Comment by sselvara** [comment]
Implemented as part the PR #201
