### ISSUE TITLE
[Cleanup] Remove unrequired docs from sharepoint

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/fonterra-fernleaf#191]

**Comment by asthabh23** [comment]
Images to be cleaned from sharepoint

**Comment by gauthamksn** [comment]
Removed all unused images. Please validate.

**Comment by asthabh23** [comment]
Is this tested that nothing on any page breaks because of any image removed? @gauthamksn

**Comment by gauthamksn** [comment]
Only unused images were the three gifs I uploaded for testing. Everything else is required.
