### ISSUE TITLE
[Header] Implement and style header

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/fonterra-fernleaf#2]
- [ ] Desktop version
![Screenshot 2023-07-21 at 1 06 37 PM](https://github.com/hlxsites/fonterra-fernleaf/assets/76686725/f0bccefe-720c-4a3d-ab8a-e09adf00d57e)

- [ ] Mobile version
<img width="392" alt="Screenshot 2023-07-21 at 1 07 07 PM" src="https://github.com/hlxsites/fonterra-fernleaf/assets/76686725/5e20cb70-7035-4f43-b911-c01ff114ad82">

- [ ] In Mobile view, create multi level navigation menu and move the hamburger to the right side.

**Comment by asthabh23** [comment]
@ParthasharathiB , progressive commits related to the assigned issue would be helpful to check along the status. If there is anything where some help is needed, please do let the team know.

**Comment by ParthasharathiB** [comment]
@asthabh23 I've committed my first level implementation to the _2-header_ branch. Currently working on mobile views and some small tweaks in header section.

https://2-header--fonterra-fernleaf--hlxsites.hlx.page/en

**Comment by asthabh23** [comment]
great! thanks @ParthasharathiB for the update
