### ISSUE TITLE
[Product Page] Implement Carousel

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/fonterra-fernleaf#20]
https://www.fernleaf.com.my/en/products.html

<img width="1179" alt="Screenshot 2023-07-26 at 2 57 09 PM" src="https://github.com/hlxsites/fonterra-fernleaf/assets/76686725/fd5010b8-51f2-4d92-8d6c-57d016ec2757">

<img width="613" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/185a4f9c-dc22-4afd-bff2-a78de9265bbd">

**_Recipe tags are as follow:_**

- Breakfast
- Lunch
- Dinner
- Snacks
- Dessert

**_Product tags:_**

- Milk Powder
- UHT Milk
- Yoghurt
- CalciYum

**Comment by mkbansal1** [comment]
Carousel on Product listing page is out of scope.
Carousel on Recipe Detail and Product detail page needs to be implemented based on tags.

**Comment by asthabh23** [comment]
@mkbansal1 @ujjwal5 
we shall consider this autoblocked for implementation

**Comment by mkbansal1** [comment]
@asthabh23 Carousel needs to be rendered based on taxonomy, which means, editors wont author anything in block/document, they will just add a single column table with block name (Carousel).

Am I missing something? Happy to understand if we can achieve this with autoblocking in a simple way.

**Comment by asthabh23** [comment]
@mkbansal1 , yes, the approach to render carousel would be tag based (I have already asked for the mapping of tags with product/recipe pages to the customer - seems the product tags shared by customer are direct to map to the product pages that we have, we can proceed with those till we have particular responses for recipe pages)

Further, considering the autoblocking approach, author shouldn't have to remember that they have to add even an empty block on each recipe/product page for the carousel to get rendered. So no need to have the single column table added to the pages.

Sharing a reference autoblock example:
https://github.com/hlxsites/fcbayern/blob/c8f34c1cbae40401001f8fcb1ba77c5e7e1a0cf3/scripts/scripts.js#L702

(you need to trigger it in decorateMain before blocks are decorated. use getMetadata to determine if and what should be auto-blocked)

**Comment by mkbansal1** [comment]
@asthabh23 i cant access the link provided.

**Comment by asthabh23** [comment]
@mkbansal1 its in the hlxsites org itself, should be accessible. What response you get when you hit the link?

**Comment by ujjwal5** [comment]
@asthabh23 not accessible for me too, returns a 404. Permission issue maybe ?

**Comment by asthabh23** [comment]
oh, the repo is private. Just checked!

I can share the function separately meanwhile. Will try to find some other reference too to be shared.

**Comment by mkbansal1** [comment]
@asthabh23 
So on high level, you are recommending adding a carousal block automatically on Product and Recipe templates, right?

**Comment by asthabh23** [comment]
exactly @mkbansal1

**Comment by mkbansal1** [comment]
What if they dont want to have carousal on any of such page? we will loose authoring capability here as we are assuming to always have a carousal on product/recipe template page

**Comment by asthabh23** [comment]
yes, that is the assumption as it is same across all the pages (in the current site). We wouldn't want the authors to have to go to pages specifically to add empty block. Anyhow explore more recipes/products will be part of all the recipe/product pages and they really don't want much control around authoring for this as discussed in customer call.

**Comment by mkbansal1** [comment]
@asthabh23 I suggest giving this control to Editors, as business users usually know the current state. We should provide flexible solutions and not bound them with such restrictions.

**Comment by asthabh23** [comment]
@mkbansal1 @ujjwal5 
If authors would really want to turn it on or off, we can handle that at page metadata level. Adding a property like `explore more recipes = yes` and using  `getMetadata('explore-more-recipes')` before adding the auto-block. 

Reference example: https://github.com/adobe/express-website/blob/stage/express/scripts/scripts.js#L1792

I think it would be good to add once this requirement really comes up. But yes, overall approach should be autoblocking in this case. I would not prefer adding empty carousel block across pages at content level.

**Comment by ujjwal5** [comment]
@asthabh23 can a recipe/product have multiple tags? Like both lunch and dinner ?
If yes, do we need to show all recipes for lunch and dinner in the carousel ?

**Comment by asthabh23** [comment]
@ujjwal5 yes, recipes/product can have multiple tags
On the recipes pages, I don't see any pattern of the listed recipes though.. I mean even a dessert is listed under Chicken Biryani.
But yes, one dessert is surely listed on each recipe detail page carousel.

Lets consider below:
- Recipe Carousel can have any random three recipes (one dessert, one breakfast, one lunch/dinner).
We are still waiting for tags mapping from customer. But I would like to see what tags we have finalised at our end.

@mkbansal1 @sselvara , can you please share this tag list with me corresponding to the recipes?
i think a discussion around this should be good to finalise it

**Comment by ujjwal5** [comment]
So are we limiting our recipe carousel to have only 3 items with 3 categories (dessert, breakfast, lunch/dinner)? Lunch/Dinner is to be considered as 1 category.

Also, what about products page carousel, what tags are we using in them ?

**Comment by asthabh23** [comment]
Tags are mentioned on the channel, @mkbansal1 can you please share details of mapping and sync with @ujjwal5 on this?
It would be good if you could please share the mapping with me too

**Comment by asthabh23** [comment]
@ujjwal5 @mkbansal1 
As discussed, let's proceed with the finalised approach as below:
- Add items to the carousel as - picking up recipes/products from the list randomly and render it (excluding the product/recipe page person is already seeing)
- Making number of recipes/products configurable to be added/modify easily later.
