### ISSUE TITLE
[Keyboard Accessibility] Home page focus effect

### ISSUE THREAD

**Issue by gauthamksn** [hlxsites/fonterra-fernleaf#209]
**Current:**
https://main--fonterra-fernleaf--hlxsites.hlx.page/en

- Fix focus effect in header:
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/92b064b7-b0bc-425d-8dec-ee071b78cc42)

- Fix tab Index order in footer:
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/0624ad98-15fb-4917-b3bd-94b2a64dedbd)

- Fix facbook logo focus effect:
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/002b0483-4517-4ab3-8ba2-07a4b60894b9)

**Expected:** 
https://www.fernleaf.com.my/en.html
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/c14f1f09-17d6-41c0-b09a-89a4899c9722)
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/8e5b2d2d-0e09-4b5f-a156-14c796d47a15)
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/9d160881-4297-4fa1-8103-3d725efabbb3)

**Comment by sselvara** [comment]
@gauthamksn, we can keep the tab order as per the current implementation as it follows left to right navigation order wherein their current site is following right to left navigation order only for footer. 
@asthabh23 FYI.

**Comment by asthabh23** [comment]
what we have now seems fine, unmerged PR closed. closing this issue as well.
