### ISSUE TITLE
[Keyboard Accessibility] Fix Focus effect of calciyum listing page

### ISSUE THREAD

**Issue by gauthamksn** [hlxsites/fonterra-fernleaf#214]
Current:
https://main--fonterra-fernleaf--hlxsites.hlx.page/en/products/calciyum
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/25daeb08-d812-4c59-8d50-77717646f6bf)

Expected:
https://www.fernleaf.com.my/en/products/calciyum.html
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/c1c8d6c7-44bd-41c7-b75d-f9948ccf1183)

**Comment by sselvara** [comment]
Will be resolved as part of the PR #216
