### ISSUE TITLE
Fix Link styles in About us Page

### ISSUE THREAD

**Issue by gauthamksn** [hlxsites/fonterra-fernleaf#215]
Fix spacing issue for links in about us page.

Current:
https://main--fonterra-fernleaf--hlxsites.hlx.page/en/about-us
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/6a8f5185-7c30-433b-be25-a795e28361a3)

Expected:
https://www.fernleaf.com.my/en/about-us.html
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/141001403/2f840279-de77-487b-b356-d8df594f8353)

**Comment by sselvara** [comment]
Will be resolved as part of the PR #216.
