### ISSUE TITLE
[UAT] Carousel variation for Products landing page

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/fonterra-fernleaf#238]
![Screenshot 2023-09-13 at 12 33 47 PM](https://github.com/hlxsites/fonterra-fernleaf/assets/76686725/1a5b8025-e643-41c3-929d-c315175063c1)

Points to consider:
- Add a new variation to carousal "product-landing"
- No. of items visible in a view: 3 (for new variation)
- Max number of items in carousel : 7 (this would apply for carousel on product detailing page as well) - to be updated in configuration
- Add negative margin, to overlay carousal with hero, applicable for new variation.

**Comment by ujjwal5** [comment]
Raised another PR to update carousel-wrapper margins for smaller viewports to keep carousel images and splash image superimposed on each other.

**Comment by ujjwal5** [comment]
https://github.com/hlxsites/fonterra-fernleaf/pull/260 fixes carousel left/right button click
