### ISSUE TITLE
[UAT] Update redirects sheet

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/fonterra-fernleaf#242]
Update redirects sheet to reflect on the right URLs for stories and tips articles (in /en and /ms)

**Comment by mkbansal1** [comment]
@asthabh23 
Noticed an issue with the story page listing on MS language, The live site sitemap has 10 story pages for MS, all 10 links are accessible, but the actual story page shows only 6 story

It means, 4 story pages are not listed, but actually exist
<img width="1398" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/670706d7-4732-4e7f-98c1-87a10440aead">
<img width="432" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/1aba68ec-d564-43e4-ac16-6d1ac56bd3a0">

**Comment by mkbansal1** [comment]
@asthabh23 The redirect sheet is up to date now. Please validate it.

**Comment by asthabh23** [comment]
looks good!
