### ISSUE TITLE
[Stories-and-tips] Implement Print

### ISSUE THREAD

**Issue by sselvara** [hlxsites/fonterra-fernleaf#25]
<img width="684" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/25244481/509cc04f-a092-4cf9-ab11-2fe50dc315f3">

-----

 **Print View without header and footer**

<img width="1025" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/25244481/2cbe4072-f83f-4574-b94b-7abc3fc0dee9">

**Comment by mkbansal1** [comment]
Approach: Implement JS logicin delayed.js to check body class, if its "story-tips" then render the print icon above H1 tag, and implement print.css

@sselvara  @asthabh23
