### ISSUE TITLE
[GTM] Implement GTM

### ISSUE THREAD

**Issue by sselvara** [hlxsites/fonterra-fernleaf#26]
@asthabh23 Please confirm scope of GTM

**Comment by asthabh23** [comment]
@sselvara @mkbansal1 
we will consider implementing GTM as we do on other Franklin sites in delayed.js
Reference: https://github.com/hlxsites/moleculardevices/blob/07cc10903ffd3f87530a81a46367a4e9ab94e1e0/scripts/delayed.js#L67

**Comment by asthabh23** [comment]
@mkbansal1 @sselvara  I have asked the customer for the specs around GTM implementation to consider the key KPIs, response awaited.
Meanwhile we would consider integration as here: https://github.com/hlxsites/moleculardevices/blob/07cc10903ffd3f87530a81a46367a4e9ab94e1e0/scripts/delayed.js#L67
to begin with.

**Comment by mkbansal1** [comment]
@asthabh23 Live site is using key "GTM-NX6JQZG" for GTM, if we use it, we will start pushing tracking to live GTM.
Is it ok for client has any Test key for development purpose ?

**Comment by asthabh23** [comment]
Customer response awaited on this, adding on-hold label

**Comment by asthabh23** [comment]
@sselvara @mkbansal1 
We have a response from customer on this, they are ok to have us use prod gtm-id for integration/testing, let's discuss further on this in our call today
