### ISSUE TITLE
Update GTM Script

### ISSUE THREAD

**Issue by mkbansal1** [hlxsites/fonterra-fernleaf#264]
Update GTM script to include noscript part also

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'[https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f)](https://www.googletagmanager.com/gtm.js?id=%27+i+dl;f.parentNode.insertBefore(j,f));
})(window,document,'script','dataLayer','GTM-NX6JQZG');</script>

<noscript><iframe src=https://www.googletagmanager.com/ns.html?id=GTM-NX6JQZG
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by asthabh23** [comment]
@mkbansal1 please see as reference:
https://github.com/hlxsites/caesars-careers/blob/9ae162386fcbcfa5501c96ee4991f392a25d83e8/careers/scripts/delayed.js#L48
