### ISSUE TITLE
[Story] Share feature

### ISSUE THREAD

**Issue by mkbansal1** [hlxsites/fonterra-fernleaf#27]
https://www.fernleaf.com.my/en/stories-and-tips/susu-punca-anak-hiperaktif-kurang-selera-makan.html
<img width="695" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/2ba6aa29-e63b-4a4b-9a2d-4f01e4e08183">

**Comment by mkbansal1** [comment]
@asthabh23 Share is not functional on live site, please confirm if its in scope and need to be fixed.

**Comment by asthabh23** [comment]
@mkbansal1 , already shared with customer, will follow-up on this. For now, just a placeholder for 'share' can be fine till we get confirmation
