### ISSUE TITLE
[Recipe] Related recipe

### ISSUE THREAD

**Issue by mkbansal1** [hlxsites/fonterra-fernleaf#32]
<img width="869" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/8bbf7956-887e-4433-b2f1-1db270aee560">

**Comment by mkbansal1** [comment]
@asthabh23 Please confirm logic to identify related recipes, or will it be manually selected on each recipe?

**Comment by asthabh23** [comment]
@mkbansal1 Will discuss this in our call today

**Comment by mkbansal1** [comment]
Related Recipe will be implements by carousel block #20
