### ISSUE TITLE
[Products] Related products

### ISSUE THREAD

**Issue by mkbansal1** [hlxsites/fonterra-fernleaf#33]
<img width="869" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/1252090a-215c-46bd-aab4-8c4528d9c33c">

**Comment by mkbansal1** [comment]
@asthabh23 Please confirm logic to identify related products, or will it be manually selected on each product?

**Comment by asthabh23** [comment]
@mkbansal1 , there are few options to do this, definitely won't be manually. I am still awaiting customer response around the product pages implementation. This would possibly be covered in kick-off meet. Till then let's hold this part.

**Comment by mkbansal1** [comment]
Related Product will be implements by carousel block #20

**Comment by mkbansal1** [comment]
Closing this card.
