### ISSUE TITLE
[Footer] Language Selector

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/fonterra-fernleaf#4]
- [ ] Create the pop-up (the button to open it should be implemented in https://github.com/hlxsites/fonterra-fernleaf/issues/3 )
- [ ] After selecting a language, redirect to the appropriate page
- [ ] Implement this as a separate script in scripts directory, not a block.

<img width="977" alt="Screenshot 2023-07-21 at 1 32 45 PM" src="https://github.com/hlxsites/fonterra-fernleaf/assets/76686725/29771ddc-bbca-451a-95da-70dc49d4bae5">

**Comment by mkbansal1** [comment]
@asthabh23 Please arrange missing images in this screen
