### ISSUE TITLE
[Header] Required Bug fixes

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/fonterra-fernleaf#48]
Few fixes required in header:
English version:

- [ ] Recipes list vertical scroll needs to be fixed.
- [ ] Below 900px, "Fernleaf" logo is shifted upwards, should be centrally aligned between the header.
![Screenshot 2023-07-31 at 9 31 06 AM](https://github.com/hlxsites/fonterra-fernleaf/assets/76686725/dd9fcdb8-5a3a-442e-bba5-04bad6d9e08e)

- [x] Clicking logo should redirect to homepage again - https://main--fonterra-fernleaf--hlxsites.hlx.page/en

Malay Version:

- [x] English version styles are not applicable here yet.\
- [x] Header is still in English, needs to be fixed, also hamburger is not clickable below 900px.
![Screenshot 2023-07-31 at 9 32 57 AM](https://github.com/hlxsites/fonterra-fernleaf/assets/76686725/be424e0c-c30e-4d85-9b6a-e8e16b1ead30)

- [x] All links in header redirect to English version pages, need fix at authoring level.

**Comment by asthabh23** [comment]
@mkbansal1 

- as discussed earlier, we can fix the vertical scrollbar at our end. No two-column style change. We will proceed as per the layout we see on original site.
- Alignment is correct, I just mentioned it should be vertically centered.

**Comment by asthabh23** [comment]
@mkbansal1 @sselvara any update on this?

**Comment by mkbansal1** [comment]
Fixed issues:

- [x] English version styles are not applicable here yet.
- [x] Header is still in English, needs to be fixed, also hamburger is not clickable below 900px.
- [x] All links in header redirect to English version pages, need fix at authoring level.

Header logo and navigation scroll is implemented as per live site, lets discuss our recommendations with client in tomorrow’s kickoff call.

**Comment by mkbansal1** [comment]
@asthabh23 Issues reported in this card is fixed except below two.

- Recipes list vertical scroll needs to be fixed - Recipe dropdown is out of scope now.
-  Below 900px, "Fernleaf" logo is shifted upwards, should be centrally aligned between the header. - Lets keep it as it is, as it;s implemented as per live site.

If you are aligned, we can close this card.

@sselvara

**Comment by asthabh23** [comment]
@mkbansal1 @sselvara , I just reviewed the header, found a bug:
- Below 900px, Clicking on hamburger to display menu doesn't work. If it does by chance then internal menu options aren't clickable for me.

I think this needs a fix before we close the issue. Please check if you are able to replicate the behaviour

**Comment by asthabh23** [comment]
This seems to be fixed, closing the card.
