### ISSUE TITLE
[Design] Implement 301 redirect rules for URLs with .html

### ISSUE THREAD

**Issue by mkbansal1** [hlxsites/fonterra-fernleaf#5]
Franklin supports extn less urls only.
To handle .html, we need to apply 301 redirection using redirects.xlxs file from .html to extn less page

This activity needs to be done once pages are ready on Franklin.

**Comment by mkbansal1** [comment]
@asthabh23  I have placed 301 redirects from .html to Franklin pages and also pointed the old pages (eg. Chinese article) to the parent page.
https://main--fonterra-fernleaf--hlxsites.hlx.live/redirects.json

Please perform a sanity at your end also, before we close this card.

**Comment by asthabh23** [comment]
sure, I will take a look!

**Comment by asthabh23** [comment]
I have checked this, lgtm!
We would confirm the links with customer now in UAT

**Comment by asthabh23** [comment]
This has been shared with the customer
