### ISSUE TITLE
[Hero] Issues

### ISSUE THREAD

**Issue by mkbansal1** [hlxsites/fonterra-fernleaf#50]
- banner is overlapping navigation
https://14-implement-hero-banner--fonterra-fernleaf--hlxsites.hlx.page/en/products/uht-milk
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/87a91ea8-7fe0-4643-8170-b12f2231235a)

- Home page - whitespace b/w banner
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/d1098d54-9861-4144-ab9d-e456e875f249)

- Home page - mobile view - reduce height of banner and set image as bottom aligned
<img width="407" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/2bd78e29-16bd-413e-ab82-c9330564e2c8">

- Code review
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/8cd46cba-a561-4d37-91a6-b4615794b061)

- Code review
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/02fc3e23-9e8e-4d9b-855b-be4d1858c2a6)

**Comment by noormd08** [comment]
All the issues and code review comments are taken care except the 3rd issue - image resizing. This can't be achieved with min-height based on existing site due the image height.
