### ISSUE TITLE
[Recipes] Add star ratings on recipe cards

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/fonterra-fernleaf#56]
Add star ratings card to recipe page as on original site:
![Screenshot 2023-07-31 at 7 40 46 PM](https://github.com/hlxsites/fonterra-fernleaf/assets/76686725/ed9d813f-3ca4-4eca-8ee4-7fb6cb7e7b11)

**Comment by mkbansal1** [comment]
As agreed in client call today, star rating is out of scope.
