### ISSUE TITLE
Products and Recipes tagging

### ISSUE THREAD

**Issue by mkbansal1** [hlxsites/fonterra-fernleaf#73]
Apply tags in Page metadata for Products and Recipies
**_Recipe tags are as follow:_**

- Breakfast
- Lunch
- Dinner
- Snacks
- Dessert

**_Product tags:_**

- Milk Powder
- UHT Milk
- Yoghurt
- CalciYum

**Comment by mkbansal1** [comment]
@asthabh23  Please provide product/recipe mapping with tags.

**Comment by asthabh23** [comment]
@mkbansal1 This is pending with customer, we discussed we will proceed with what we already have, the product tags mapping seems to be straight forward. 
have we done some mapping for recipes as well? if yes, can you please share that?

**Comment by asthabh23** [comment]
I have put a follow-up message on this to the customer though.

**Comment by mkbansal1** [comment]
@asthabh23 I have added this card, as we have to perform this activity once the client confirms the mapping.

**Comment by mkbansal1** [comment]
As agreed with @asthabh23  @sselvara  @ujjwal5 , we wont be using tags in carousal logic, so this activity is no more needed.
