### ISSUE TITLE
Accessibility and performance issues - Part-2

### ISSUE THREAD

**Issue by mkbansal1** [hlxsites/fonterra-fernleaf#78]
- [ ] Background / Foreground color issue across multiple pages

<img width="802" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/023fa2bf-92ef-44d4-b19b-fca0520fc358">
Recipe list page - https://main--fonterra-fernleaf--hlxsites.hlx.page/en/recipes
<img width="761" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/e4624c30-892e-421a-b32d-00e15cd966e1">

**Comment by asthabh23** [comment]
@mkbansal1 @sselvara 
I see the button colors would be updated for accessibility fixes, just fyi, the content inside button needs to be fully displayed on home page: https://main--fonterra-fernleaf--hlxsites.hlx.page/en (considering not to track this separately, we can fix this in this card itself)
<img width="898" alt="Screenshot 2023-08-07 at 5 09 23 PM" src="https://github.com/hlxsites/fonterra-fernleaf/assets/76686725/c05b8291-c36d-4872-8ee8-3f25323f7eab">

**Comment by sselvara** [comment]
@asthabh23, below are the new colors that will be used to address accessibility issues.

- Button text color to support accessibility: #663300, 
https://webaim.org/resources/contrastchecker/?fcolor=663300&bcolor=FEDF00

- Recipe list page - Serves and duration : #595959
- https://webaim.org/resources/contrastchecker/?fcolor=595959&bcolor=FFFFFF

**Comment by mkbansal1** [comment]
@sselvara Lets implement it with your recommended colors.
